name: Commitlint

on:
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Validate commit messages and generate report
        run: |
          mkdir -p reports
          # redirige la salida de commitlint a un archivo txt
          npx @commitlint/cli --from=${{ github.event.pull_request.base.sha }} --to=HEAD > reports/commitlint-report.txt || true
          cat reports/commitlint-report.txt

      - name: Upload commitlint report
        uses: actions/upload-artifact@v4
        with:
          name: commitlint-report
          path: reports/commitlint-report.txt